### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by scottBowles** [scottBowles/airel-client#3]
A favicon is the little icon that's displayed in the browser tab.

If anyone wants to find or make something for it, I can turn any image, text, or icon into a favicon. It just needs to look decent scaled down that small.

**Comment by GlitterSoap** [comment]
what about something like a yellow circle top left and red circle bottom right on a midnight blue field?

**Comment by scottBowles** [comment]
I like it. Want to try to make that? If you can make the image I can turn it into a favicon. If not, I'll get around it to eventually.

**Comment by GlitterSoap** [comment]
![Screenshot_20220628-235430-659](https://user-images.githubusercontent.com/108367871/176361923-514ef433-ed1b-4fd5-b63f-cf97ce535806.png)

**Comment by GlitterSoap** [comment]
i figured, why not in the style of our in-game content?

**Comment by scottBowles** [comment]
Love and it just went live
